<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: easymicro.proto

namespace Pb\Easymicro;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.easymicro.EMReq</code>
 */
class EMReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string traceID = 1;</code>
     */
    private $traceID = '';
    /**
     * Generated from protobuf field <code>string cmd = 2;</code>
     */
    private $cmd = '';
    /**
     * Generated from protobuf field <code>int32 seq = 3;</code>
     */
    private $seq = 0;
    /**
     * Generated from protobuf field <code>bytes reqData = 4;</code>
     */
    private $reqData = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $traceID
     *     @type string $cmd
     *     @type int $seq
     *     @type string $reqData
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Easymicro::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string traceID = 1;</code>
     * @return string
     */
    public function getTraceID()
    {
        return $this->traceID;
    }

    /**
     * Generated from protobuf field <code>string traceID = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTraceID($var)
    {
        GPBUtil::checkString($var, True);
        $this->traceID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cmd = 2;</code>
     * @return string
     */
    public function getCmd()
    {
        return $this->cmd;
    }

    /**
     * Generated from protobuf field <code>string cmd = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCmd($var)
    {
        GPBUtil::checkString($var, True);
        $this->cmd = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 seq = 3;</code>
     * @return int
     */
    public function getSeq()
    {
        return $this->seq;
    }

    /**
     * Generated from protobuf field <code>int32 seq = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSeq($var)
    {
        GPBUtil::checkInt32($var);
        $this->seq = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes reqData = 4;</code>
     * @return string
     */
    public function getReqData()
    {
        return $this->reqData;
    }

    /**
     * Generated from protobuf field <code>bytes reqData = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setReqData($var)
    {
        GPBUtil::checkString($var, False);
        $this->reqData = $var;

        return $this;
    }

}

