<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: easymicro.proto

namespace Pb\Easymicro;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.easymicro.EMRsp</code>
 */
class EMRsp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string traceID = 1;</code>
     */
    private $traceID = '';
    /**
     * Generated from protobuf field <code>string cmd = 2;</code>
     */
    private $cmd = '';
    /**
     * Generated from protobuf field <code>int32 seq = 3;</code>
     */
    private $seq = 0;
    /**
     * Generated from protobuf field <code>int32 rspCode = 4;</code>
     */
    private $rspCode = 0;
    /**
     * Generated from protobuf field <code>string rspMsg = 5;</code>
     */
    private $rspMsg = '';
    /**
     * Generated from protobuf field <code>bytes rspData = 6;</code>
     */
    private $rspData = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $traceID
     *     @type string $cmd
     *     @type int $seq
     *     @type int $rspCode
     *     @type string $rspMsg
     *     @type string $rspData
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Easymicro::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string traceID = 1;</code>
     * @return string
     */
    public function getTraceID()
    {
        return $this->traceID;
    }

    /**
     * Generated from protobuf field <code>string traceID = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTraceID($var)
    {
        GPBUtil::checkString($var, True);
        $this->traceID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cmd = 2;</code>
     * @return string
     */
    public function getCmd()
    {
        return $this->cmd;
    }

    /**
     * Generated from protobuf field <code>string cmd = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCmd($var)
    {
        GPBUtil::checkString($var, True);
        $this->cmd = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 seq = 3;</code>
     * @return int
     */
    public function getSeq()
    {
        return $this->seq;
    }

    /**
     * Generated from protobuf field <code>int32 seq = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSeq($var)
    {
        GPBUtil::checkInt32($var);
        $this->seq = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 rspCode = 4;</code>
     * @return int
     */
    public function getRspCode()
    {
        return $this->rspCode;
    }

    /**
     * Generated from protobuf field <code>int32 rspCode = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setRspCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->rspCode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string rspMsg = 5;</code>
     * @return string
     */
    public function getRspMsg()
    {
        return $this->rspMsg;
    }

    /**
     * Generated from protobuf field <code>string rspMsg = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setRspMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->rspMsg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes rspData = 6;</code>
     * @return string
     */
    public function getRspData()
    {
        return $this->rspData;
    }

    /**
     * Generated from protobuf field <code>bytes rspData = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setRspData($var)
    {
        GPBUtil::checkString($var, False);
        $this->rspData = $var;

        return $this;
    }

}

